/**
 * HTTP client for the MaskForge sidecar API (see docs/IPC_CONTRACT.md).
 *
 * The sidecar port is not known at build time — it is assigned by the OS
 * and reported to the Tauri shell, which exposes it through the
 * `get_sidecar_port` IPC command. When running outside Tauri (plain
 * `npm run dev` in a browser, for local frontend iteration) we fall back to
 * the VITE_SIDECAR_PORT env var so the app still boots against a manually
 * started sidecar.
 *
 * The sidecar also requires a per-launch auth token (X-MaskForge-Token
 * header) on every request but /health — 127.0.0.1 is reachable by any
 * local process or browser tab, not just this app, and the port alone
 * isn't a secret. The token is generated by the sidecar itself and handed
 * to us the same way the port is, via `get_sidecar_token`; a malicious
 * page that merely guesses the port cannot forge it.
 */

import type {
  ApplyAutoSegmentComponentRequest,
  ApplyAutoSegmentRequest,
  AutoSegmentRequest,
  AutoSegmentResult,
  ClassPalette,
  DeletedResult,
  DiscoveryConfig,
  HealthResult,
  RemapRequest,
  RemapResult,
  SaveConfig,
  SaveMaskResult,
  SceneEntry,
  SceneLayers,
  SceneStats,
  SessionState,
  ShadowGenerateRequest,
  ShadowPreset,
  LayerData,
  StatsExportRequest,
  StatsExportResult,
  ToolRequest,
  ToolResult,
} from "@/types/api";

const API_PREFIX = "/api/v1";

let cachedPort: number | null = null;
let portPromise: Promise<number> | null = null;
let cachedToken: string | null = null;
let tokenPromise: Promise<string> | null = null;

/** True when running inside the Tauri webview (as opposed to a plain browser). */
function hasTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI__" in window;
}

function tauriInvoke<T>(cmd: string): Promise<T> {
  const tauriGlobal = (window as unknown as {
    __TAURI__: { core: { invoke: (cmd: string) => Promise<T> } };
  }).__TAURI__;
  return tauriGlobal.core.invoke(cmd);
}

async function resolvePort(): Promise<number> {
  if (cachedPort !== null) return cachedPort;
  if (portPromise) return portPromise;

  portPromise = (async () => {
    if (hasTauri()) {
      try {
        const port = await tauriInvoke<number>("get_sidecar_port");
        if (typeof port === "number" && Number.isFinite(port) && port > 0) {
          cachedPort = port;
          return port;
        }
        throw new Error(`get_sidecar_port returned an invalid value: ${String(port)}`);
      } catch (err) {
        throw new Error(
          `Failed to resolve sidecar port via Tauri IPC: ${
            err instanceof Error ? err.message : String(err)
          }`,
        );
      }
    }

    const fallback = import.meta.env.VITE_SIDECAR_PORT;
    if (fallback) {
      const parsed = Number(fallback);
      if (Number.isFinite(parsed) && parsed > 0) {
        cachedPort = parsed;
        return parsed;
      }
    }

    throw new Error(
      "No sidecar port available: not running inside Tauri and VITE_SIDECAR_PORT is unset. " +
        "Set VITE_SIDECAR_PORT in a .env.local file to point at a manually started sidecar.",
    );
  })();

  try {
    return await portPromise;
  } finally {
    portPromise = null;
  }
}

async function resolveToken(): Promise<string> {
  if (cachedToken !== null) return cachedToken;
  if (tokenPromise) return tokenPromise;

  tokenPromise = (async () => {
    if (hasTauri()) {
      try {
        const token = await tauriInvoke<string>("get_sidecar_token");
        if (typeof token === "string" && token.length > 0) {
          cachedToken = token;
          return token;
        }
        throw new Error("get_sidecar_token returned an empty value");
      } catch (err) {
        throw new Error(
          `Failed to resolve sidecar auth token via Tauri IPC: ${
            err instanceof Error ? err.message : String(err)
          }`,
        );
      }
    }

    // Browser-fallback dev mode: VITE_SIDECAR_PORT users are expected to
    // set the same MASKFORGE_TOKEN the manually started sidecar printed
    // (it reads the env var back if present — see api/server.py).
    const fallback = import.meta.env.VITE_SIDECAR_TOKEN;
    if (fallback) {
      cachedToken = fallback;
      return fallback;
    }

    throw new Error(
      "No sidecar auth token available: not running inside Tauri and VITE_SIDECAR_TOKEN is unset.",
    );
  })();

  try {
    return await tokenPromise;
  } finally {
    tokenPromise = null;
  }
}

export class SidecarUnavailableError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SidecarUnavailableError";
  }
}

export class ApiError extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.name = "ApiError";
    this.status = status;
  }
}

async function request<T>(
  path: string,
  init?: RequestInit,
): Promise<T> {
  let port: number;
  let token: string;
  try {
    [port, token] = await Promise.all([resolvePort(), resolveToken()]);
  } catch (err) {
    throw new SidecarUnavailableError(
      err instanceof Error ? err.message : String(err),
    );
  }

  const url = `http://127.0.0.1:${port}${API_PREFIX}${path}`;
  let response: Response;
  try {
    response = await fetch(url, {
      ...init,
      headers: {
        "Content-Type": "application/json",
        "X-MaskForge-Token": token,
        ...init?.headers,
      },
    });
  } catch (err) {
    throw new SidecarUnavailableError(
      `Could not reach sidecar at ${url}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }

  if (!response.ok) {
    let detail = response.statusText;
    try {
      const body = await response.json();
      if (body && typeof body === "object" && "detail" in body) {
        detail = String((body as { detail: unknown }).detail);
      }
    } catch {
      // body wasn't JSON, keep statusText
    }
    throw new ApiError(response.status, detail);
  }

  if (response.status === 204) {
    return undefined as T;
  }
  return (await response.json()) as T;
}

function get<T>(path: string): Promise<T> {
  return request<T>(path, { method: "GET" });
}

function post<T>(path: string, body?: unknown): Promise<T> {
  return request<T>(path, {
    method: "POST",
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

function put<T>(path: string, body: unknown): Promise<T> {
  return request<T>(path, { method: "PUT", body: JSON.stringify(body) });
}

function del<T>(path: string): Promise<T> {
  return request<T>(path, { method: "DELETE" });
}

/** Exposed for the status bar to display connection state without a full request. */
export async function getSidecarPort(): Promise<number> {
  return resolvePort();
}

/** Exposed for callers that need to authenticate a non-fetch channel (the
 * progress WebSocket, which can't set headers — see progressSocket.ts). */
export async function getSidecarToken(): Promise<string> {
  return resolveToken();
}

export async function resolveBaseUrl(): Promise<string> {
  const port = await resolvePort();
  return `http://127.0.0.1:${port}${API_PREFIX}`;
}

/**
 * Opens the native folder picker (Tauri's `pick_folder` command, backed by
 * tauri-plugin-dialog on the Rust side). Returns null if the user cancels,
 * or if running outside Tauri (plain browser dev mode has no native dialog
 * to fall back to).
 */
export async function pickFolder(): Promise<string | null> {
  if (!hasTauri()) return null;
  try {
    const tauriGlobal = (window as unknown as {
      __TAURI__: { core: { invoke: (cmd: string) => Promise<string | null> } };
    }).__TAURI__;
    return await tauriGlobal.core.invoke("pick_folder");
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

export function getHealth(): Promise<HealthResult> {
  return get<HealthResult>("/health");
}

// ---------------------------------------------------------------------------
// Scenes
// ---------------------------------------------------------------------------

export function getScenes(sessionId: string): Promise<SceneEntry[]> {
  const query = new URLSearchParams({ session_id: sessionId });
  return get<SceneEntry[]>(`/scenes?${query.toString()}`);
}

export function discoverScenes(config: DiscoveryConfig): Promise<SceneEntry[]> {
  return post<SceneEntry[]>("/scenes/discover", config);
}

export function getSceneLayers(sceneId: string): Promise<SceneLayers> {
  return get<SceneLayers>(`/scenes/${encodeURIComponent(sceneId)}/layers`);
}

// ---------------------------------------------------------------------------
// Masks / tools
// ---------------------------------------------------------------------------

export function applyTool(
  sceneId: string,
  toolRequest: ToolRequest,
): Promise<ToolResult> {
  return post<ToolResult>(
    `/masks/${encodeURIComponent(sceneId)}/tool`,
    toolRequest,
  );
}

export function previewAutoSegment(
  sceneId: string,
  request: AutoSegmentRequest,
): Promise<AutoSegmentResult> {
  return post<AutoSegmentResult>(
    `/masks/${encodeURIComponent(sceneId)}/auto-segment`,
    request,
  );
}

export function applyAutoSegment(
  sceneId: string,
  request: ApplyAutoSegmentRequest,
): Promise<ToolResult> {
  return post<ToolResult>(
    `/masks/${encodeURIComponent(sceneId)}/auto-segment/apply`,
    request,
  );
}

export function applyAutoSegmentComponent(
  sceneId: string,
  request: ApplyAutoSegmentComponentRequest,
): Promise<ToolResult> {
  return post<ToolResult>(
    `/masks/${encodeURIComponent(sceneId)}/auto-segment/apply-component`,
    request,
  );
}

export function discardAutoSegment(sceneId: string): Promise<DeletedResult> {
  return post<DeletedResult>(`/masks/${encodeURIComponent(sceneId)}/auto-segment/discard`, {});
}

export function saveMask(
  sceneId: string,
  saveConfig: SaveConfig,
): Promise<SaveMaskResult> {
  return post<SaveMaskResult>(
    `/masks/${encodeURIComponent(sceneId)}/save`,
    saveConfig,
  );
}

export interface UndoRedoResult {
  applied: boolean;
}

export function undoMask(sceneId: string): Promise<UndoRedoResult> {
  return post<UndoRedoResult>(`/masks/${encodeURIComponent(sceneId)}/undo`);
}

export function redoMask(sceneId: string): Promise<UndoRedoResult> {
  return post<UndoRedoResult>(`/masks/${encodeURIComponent(sceneId)}/redo`);
}

export function remapColor(
  sceneId: string,
  remapRequest: RemapRequest,
): Promise<RemapResult> {
  return post<RemapResult>(
    `/masks/${encodeURIComponent(sceneId)}/remap`,
    remapRequest,
  );
}

// ---------------------------------------------------------------------------
// Class palettes
// ---------------------------------------------------------------------------

export function getPalettes(): Promise<ClassPalette[]> {
  return get<ClassPalette[]>("/classes/palettes");
}

export function createPalette(palette: ClassPalette): Promise<ClassPalette> {
  return post<ClassPalette>("/classes/palettes", palette);
}

export function updatePalette(
  id: string,
  palette: ClassPalette,
): Promise<ClassPalette> {
  return put<ClassPalette>(`/classes/palettes/${encodeURIComponent(id)}`, palette);
}

export function deletePalette(id: string): Promise<DeletedResult> {
  return del<DeletedResult>(`/classes/palettes/${encodeURIComponent(id)}`);
}

// ---------------------------------------------------------------------------
// Sessions
// ---------------------------------------------------------------------------

export function getSessions(): Promise<SessionState[]> {
  return get<SessionState[]>("/sessions");
}

export function getSession(id: string): Promise<SessionState> {
  return get<SessionState>(`/sessions/${encodeURIComponent(id)}`);
}

export function createSession(session: SessionState): Promise<SessionState> {
  return post<SessionState>("/sessions", session);
}

export function updateSession(
  id: string,
  session: SessionState,
): Promise<SessionState> {
  return put<SessionState>(`/sessions/${encodeURIComponent(id)}`, session);
}

export function deleteSession(id: string): Promise<DeletedResult> {
  return del<DeletedResult>(`/sessions/${encodeURIComponent(id)}`);
}

// ---------------------------------------------------------------------------
// Shadow generation
// ---------------------------------------------------------------------------

export function generateShadow(
  request: ShadowGenerateRequest,
): Promise<LayerData> {
  return post<LayerData>("/shadow/generate", request);
}

export function getShadowPresets(): Promise<ShadowPreset[]> {
  return get<ShadowPreset[]>("/shadow/presets");
}

export function saveShadowPreset(preset: ShadowPreset): Promise<ShadowPreset> {
  return post<ShadowPreset>("/shadow/presets", preset);
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

export function getStats(sceneId: string): Promise<SceneStats> {
  return get<SceneStats>(`/stats/${encodeURIComponent(sceneId)}`);
}

export function exportStats(
  request: StatsExportRequest,
): Promise<StatsExportResult> {
  return post<StatsExportResult>("/stats/export", request);
}
